extend = "../Makefile.toml"

# Since it's a tool, build it for the platform we're running on
[env]
TARGET_TRIPLE = "${CARGO_MAKE_RUST_TARGET_TRIPLE}"

# Seems clippy doesn't respect TARGET_TRIPLE
[tasks.clippy]
args = ["clippy", "--target", "${CARGO_MAKE_RUST_TARGET_TRIPLE}", "--", "-Dwarnings"]

[tasks.run]
command = "cargo"
args = [
    "run",
    "--target",
    "${CARGO_MAKE_RUST_TARGET_TRIPLE}",
    "${@}",
]
